import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";

import { Theme, ThemePanel } from "@radix-ui/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Theme className="h-screen flex flex-col grow">
					<nav className="w-screen max-w-screen h-10 px-24 flex itens-center justify-between border-b-2">
						<div className="flex items-center">
							<h1 className="ml-2 text-lg font-bold">ICAPS Car Tracker</h1>
						</div>
						<div className="flex items-center">
							<a href="#" className="text-sm text-gray-600">
								Home
							</a>
							<a href="#" className="ml-4 text-sm text-gray-600">
								About
							</a>
							<a href="#" className="ml-4 text-sm text-gray-600">
								Contact
							</a>
						</div>
					</nav>
					{children}
					{/* <ThemePanel /> */}
				</Theme>
			</body>
		</html>
	);
}
