// <auto-generated />
using ICAPS_API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ICAPS_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ICAPS_API.Database.Anomaly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnomalyType")
                        .HasColumnType("INTEGER");

                    b.Property<float>("height")
                        .HasColumnType("REAL");

                    b.Property<float>("lat")
                        .HasColumnType("REAL");

                    b.Property<float>("lng")
                        .HasColumnType("REAL");

                    b.Property<float>("offset")
                        .HasColumnType("REAL");

                    b.Property<float>("width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Anomalies");
                });
#pragma warning restore 612, 618
        }
    }
}
