/* Fuzzy inference system generated by qfiscgen.m for the qFIS engine*/
/* Generated : 05-Oct-2024 19:46:22 */
/* MATLAB Version: 9.14.0.2489007 (R2023a) Update 6 */
/* Note: Based on the qFIS engine from https://github.com/kmilo17pet/qlibs */

#ifndef ICAPS2_FIS_H
#define ICAPS2_FIS_H

#ifdef __cplusplus
    extern "C" {
#endif

    void icaps2_init( void );
    void icaps2_run( Anomaly *inputs, void (*moveFunction) (float,float));

#ifdef __cplusplus
    }
#endif

#endif /* ICAPS2_FIS_H */
